### ISSUE TITLE
Symbols for circuit elements are not assumed real in symbolic analysis

### ISSUE THREAD

**Issue by RJTK** [ahkab/ahkab#32]
In symbolic.py there is a dictionary
```
enabled_assumptions = {'real':False, 'positive':False, 'complex':True}
```
Which is checked in the _symbol_factory function
```
def _symbol_factory(name, **options):
    filtered_options = {}
    for i in options:
        if options[i] and enabled_assumptions[i]:
            filtered_options.update({i:options[i]})
        else:
            pass # discarded
    return sympy.Symbol(name.upper(), **filtered_options)
```

This is preventing symbols from being produced with the real and positive assumptions, for example here:
```
R = _symbol_factory(elem.part_id.upper(), real=True,
                                      positive=True)
```
The fix is presumably just to enable these assumptions in the dictionary
```
enabled_assumptions = {'real':True, 'positive':True, 'complex':True}
```

**Comment by ggventurini** [comment]
Hi,

Thanks for your feedback. Indeed you are right. The filter has been introduced there because of issues with older versions of sympy, not relevant anymore.

Your proposed solution is indeed correct and I will merge the change soon.

Thanks.

GV
