### ISSUE TITLE
how to use the ahkab.results class ?

### ISSUE THREAD

**Issue by leoli1119** [ahkab/ahkab#35]
I want to use ahkab.results class to get AC simulation result data , but there is something wrong with it .

OS : win7 x64 sp1
python:  Python 3.4.3
python code:
----------------------------
 -*- coding: utf-8 -*-

from ahkab import results , circuit
import ahkab

cir = circuit.Circuit('Butterworth 1kHz band-pass filter')
cir.add_vsource('V1', 'n1', cir.gnd, dc_value=0., ac_value=1.)
cir.add_resistor('R1', 'n1', 'n2', 50.)
cir.add_inductor('L1', 'n2', 'n3', 0.245894)
cir.add_capacitor('C1', 'n3', 'n4', 1.03013e-07)
cir.add_inductor('L2', 'n4', cir.gnd, 9.83652e-05)
cir.add_capacitor('C2', 'n4', cir.gnd, 0.000257513)
cir.add_inductor('L3', 'n4', 'n5', 0.795775)
cir.add_capacitor('C3', 'n5', 'n6', 3.1831e-08)
cir.add_inductor('L4', 'n6', cir.gnd, 9.83652e-05)
cir.add_capacitor('C4', 'n6', cir.gnd, 0.000257513)
cir.add_capacitor('C5', 'n7', 'n8', 1.03013e-07)
cir.add_inductor('L5', 'n6', 'n7', 0.245894)
cir.add_resistor('R2', 'n8', cir.gnd, 50.)

opa = ahkab.new_op()

outfile = "E:\\Python_File\\spice_test\\outfilea"

rst = results.ac_solution(cir, .97e3, 1.03e3, 1e2, "LOG", opa, "outfile")

rst["f"]
 ---------------------------

**Comment by ggventurini** [comment]
The `ac_results class` is not to be instantiated directly, usually, but it is instantiated by the simulator to store the result of the AC analysis.

Take a look at this code, I believe it is what you meant above:

```python
from ahkab import results , circuit
import ahkab

cir = circuit.Circuit('Butterworth 1kHz band-pass filter')
cir.add_vsource('V1', 'n1', cir.gnd, dc_value=0., ac_value=1.)
cir.add_resistor('R1', 'n1', 'n2', 50.)
cir.add_inductor('L1', 'n2', 'n3', 0.245894)
cir.add_capacitor('C1', 'n3', 'n4', 1.03013e-07)
cir.add_inductor('L2', 'n4', cir.gnd, 9.83652e-05)
cir.add_capacitor('C2', 'n4', cir.gnd, 0.000257513)
cir.add_inductor('L3', 'n4', 'n5', 0.795775)
cir.add_capacitor('C3', 'n5', 'n6', 3.1831e-08)
cir.add_inductor('L4', 'n6', cir.gnd, 9.83652e-05)
cir.add_capacitor('C4', 'n6', cir.gnd, 0.000257513)
cir.add_capacitor('C5', 'n7', 'n8', 1.03013e-07)
cir.add_inductor('L5', 'n6', 'n7', 0.245894)
cir.add_resistor('R2', 'n8', cir.gnd, 50.)

opa = ahkab.new_op()
aca = ahkab.new_ac(stop=97e3, start=1.03e3, points=1e2, sweep_type="LOG")
r = ahkab.run(cir, [opa, aca])
```

Hope this helps! I will close the issue now, please don't hesitate to ask if something is not clear.
