### ISSUE TITLE
Theory behind circuit simulation

### ISSUE THREAD

**Issue by vovkd** [ahkab/ahkab#37]
Could you, please, point  me to a handful books about circuit simulation? This is an interesting topic, but without a good reference not so easy to pick up. And because i'm just an electronic hobbist i do not know where to start )))

**Comment by itdaniher** [comment]
@vovkd I'd strongly recommend you start with the "Quite Universal Circuit Simulator" technical manual at http://qucs.sourceforge.net/docs/technical/technical.pdf

There's additional content worth perusing at https://github.com/ahkab/ahkab/issues/3.
