### ISSUE TITLE
Is it possible to launch runs with multiprocess?

### ISSUE THREAD

**Issue by jchuang-bfn** [ahkab/ahkab#38]
Hi all,

I am doing a basic AC transient simulation for power distribution network.  I tried launching multiple simulation runs (with different decap scenarios) using pathos.multiprocessing ProcessingPool.  However, this crashes IPython.  I am wondering if anyone has successful done multiprocessing with ahkab.

Thanks,
Jerry

**Comment by itdaniher** [comment]
Jerry - I haven't tried this, but if you provide a minimal test case using pathos.multiprocessing that crashes the python interpretter or Ahkab code, I'd be keen to take a look. Feel free to re-open with more info.
