### ISSUE TITLE
JavaScript and other questions

### ISSUE THREAD

**Issue by hopewise** [ahkab/ahkab#39]
Did any one tried to compile the simulator to javascript?
Is it possible to alter a component attribute and keep the simulation on? or we need to reset every time a property changed ? ex: resistance value of a component changes..

How about performance? 

Is the results accurate? 

Is there a list of components that is included in this simulator?

Thanks

**Comment by itdaniher** [comment]
> Did any one tried to compile the simulator to javascript?

not insofaras I know. As it requires numpy, etc, I can imagine this would be an undertaking.

> Is it possible to alter a component attribute and keep the simulation on? 

Not presently.

> How about performance?

Pretty good, IMHO, but not comparable to a compiled SPICE engine like ngspice or spice3, etc.

> Is the results accurate?

Yes, even semi-complicated circuits provide theoretically correct answers across multiple simulation domains.

> Is there a list of components that is included in this simulator?

See https://github.com/ahkab/ahkab/blob/master/ahkab/devices.py#L36

Also included are EKV and basic diode models.
