### ISSUE TITLE
Involving Quality factor in simulations? 

### ISSUE THREAD

**Issue by kaklik** [ahkab/ahkab#41]
Hello, 
Is it possible to simulate a circuit with incorporating component's Quality factor?  I think it is an important feature because it is needed for simulation of LC filters build from real components like these inductors: http://www.tme.eu/cz/Document/2e8fe3373db00f79b69db1695f1f0867/cw.pdf

**Comment by ernwa** [comment]
That would be modeled with a series resistor. See:
https://en.wikipedia.org/wiki/Inductor#Q_factor

**Comment by itdaniher** [comment]
@kaklik I agree with @ernwa's response, closing this issue. Feel free to reopen if the response failed to address your issues.
