### ISSUE TITLE
Plot circuit

### ISSUE THREAD

**Issue by 21stio** [ahkab/ahkab#64]
Hey, 

is there a way to plot / print the circuit to get an output like the one in the README.md?

**Comment by itdaniher** [comment]
There's nothing integrated. 

I believe those images were drawn by hand for the sake of illustration. 

I've kicked around doing something based on GraphViz, but it'd not produce anything comparable to standard schematics.

Giuseppe and I talked about this several years ago - as I learned, it's an open (hard) problem in the ecad space - electrical engineers etc use a set of hard-to-represent heuristics when representing / illustrating a schematic or netlist.
