### ISSUE TITLE
Verification RC cutoff frequency 

### ISSUE THREAD

**Issue by yh2424** [ahkab/ahkab#68]
First of all, thanks for sharing SPICE code in python!

I tried to verify your code by running simple RC circuit. 
However the RC cutoff bandwidth (3dB BW) is different from analytical equation (fcutoff = 1/(2piRC)).

For example, when R=50 Ohm, C=0.2 pF then,  fcuttoff = ~15.91 GHz.
However, the follwoing code shows fcutoff = ~14.24 GHz

Could you please comment on this? 

```
import numpy as np
import ahkab
from ahkab import ahkab, circuit, time_functions

mycircuit = circuit.Circuit(title="Butterworth Example circuit", filename=None)

gnd = mycircuit.get_ground_node()

mycircuit.add_resistor("R1", n1="n1", n2="n2", value=50)
# mycircuit.add_inductor("L1", n1="n2", n2="n3", value=15.24e-3)
mycircuit.add_capacitor("C1", n1="n2", n2=gnd, value=0.2e-12)
# mycircuit.add_inductor("L2", n1="n3", n2="n4", value=61.86e-3)
# mycircuit.add_capacitor("C2", n1="n4", n2=gnd, value=155.12e-9)
# mycircuit.add_resistor("R2", n1="n4", n2=gnd, value=1.2e3)

voltage_step = time_functions.pulse(v1=0, v2=1, td=500e-9, tr=1e-12, pw=1, tf=1e-12, per=2)
mycircuit.add_vsource("V1", n1="n1", n2=gnd, dc_value=5, ac_value=1, function=voltage_step)

print mycircuit

op_analysis = ahkab.new_op()
ac_analysis = ahkab.new_ac(start=1e8, stop=5e10, points=100)
tran_analysis = ahkab.new_tran(tstart=0, tstop=1.2e-3, tstep=1e-6, x0=None)

r = ahkab.run(mycircuit, an_list=[op_analysis, ac_analysis, tran_analysis])
# r = ahkab.run(mycircuit, an_list=[ac_analysis, tran_analysis])

import pylab

fig = pylab.figure()
pylab.title(mycircuit.title + " - TRAN Simulation")
pylab.plot(r['tran']['T'], r['tran']['VN1'], label="Input voltage")
pylab.hold(True)
pylab.plot(r['tran']['T'], r['tran']['VN2'], label="output voltage")
pylab.legend()
pylab.hold(False)
pylab.grid(True)
pylab.ylim([0,1.2])
pylab.ylabel('Step response')
pylab.xlabel('Time [s]')
fig.savefig('tran_plot.png')

Gain = 10*np.log(np.abs(r['ac']['Vn2'])/np.abs(r['ac']['Vn1']))

fig = pylab.figure()
pylab.subplot(211)
pylab.plot(r['ac']['f'], Gain, 'o-')
pylab.grid(True)
pylab.ylabel('Gain(V(n2)) [dB]')
pylab.title(mycircuit.title + " - AC Simulation")
pylab.subplot(212)
pylab.grid(True)
pylab.plot(r['ac']['f'], np.abs(r['ac']['Vn2']), 'o-')
pylab.grid(True)
pylab.xlabel('Frequency [Hz]')
pylab.ylabel('abs(V(n2)) [V]')
fig.savefig('ac_plot.png')
pylab.show()
```

**Comment by itdaniher** [comment]
So, keep meaning to write a good response, but pinched for time and closing tabs so you get a short one!

Essentially, all iterative algorithms have an amount of error. Kinda definitionally. The AC analysis is iterative - https://github.com/ahkab/ahkab/blob/master/ahkab/ac.py#L292 - builds the freq-dependent impedance matricies, iterates. You're using very small (sub-picofarad) values, so the error is noticiably high. Rerun with C values a few orders of magnitude bigger and your error will be much less. 

I tested this by looking at the after-tens place freq of -3dB and adding orders of magnitude to your C value, approached that x5.91 10*10^Y Hz figure. Try either the transfer function analysis which returns a non-iterative solution or choosing a different unit set. If you check the issues you'll see similar conversations.
